<?php
/**
 * AnalyticsMetric
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AnalyticsMetric Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AnalyticsMetric {
    const UNKNOWN_METRIC = 'unknown_metric';
    const HITS_VIEW_SEARCH = 'hits_view_search';
    const HITS_VIEW_PDP = 'hits_view_pdp';
    const HITS_VIEW = 'hits_view';
    const HITS_TOCART_SEARCH = 'hits_tocart_search';
    const HITS_TOCART_PDP = 'hits_tocart_pdp';
    const HITS_TOCART = 'hits_tocart';
    const SESSION_VIEW_SEARCH = 'session_view_search';
    const SESSION_VIEW_PDP = 'session_view_pdp';
    const SESSION_VIEW = 'session_view';
    const CONV_TOCART_SEARCH = 'conv_tocart_search';
    const CONV_TOCART_PDP = 'conv_tocart_pdp';
    const CONV_TOCART = 'conv_tocart';
    const REVENUE = 'revenue';
    const RETURNS = 'returns';
    const CANCELLATIONS = 'cancellations';
    const ORDERED_UNITS = 'ordered_units';
    const DELIVERED_UNITS = 'delivered_units';
    const ADV_VIEW_PDP = 'adv_view_pdp';
    const ADV_VIEW_SEARCH_CATEGORY = 'adv_view_search_category';
    const ADV_VIEW_ALL = 'adv_view_all';
    const ADV_SUM_ALL = 'adv_sum_all';
    const POSITION_CATEGORY = 'position_category';
    const POSTINGS = 'postings';
    const POSTINGS_PREMIUM = 'postings_premium';
    

    
}


