<?php
/**
 * PostingGetFbsPostingListRequestFilter
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * PostingGetFbsPostingListRequestFilter Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostingGetFbsPostingListRequestFilter implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'postingGetFbsPostingListRequestFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'in_process_at' => '\Swagger\Client\Model\GetFbsPostingListRequestTimeRange',
        'order_created_at' => '\Swagger\Client\Model\GetFbsPostingListRequestTimeRange',
        'order_id' => 'int',
        'order_number' => 'string',
        'since' => '\DateTime',
        'status' => 'string',
        'to' => '\DateTime',
        'updated_at' => '\Swagger\Client\Model\GetFbsPostingListRequestTimeRange'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'in_process_at' => 'in_process_at',
        'order_created_at' => 'order_created_at',
        'order_id' => 'order_id',
        'order_number' => 'order_number',
        'since' => 'since',
        'status' => 'status',
        'to' => 'to',
        'updated_at' => 'updated_at'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'in_process_at' => 'setInProcessAt',
        'order_created_at' => 'setOrderCreatedAt',
        'order_id' => 'setOrderId',
        'order_number' => 'setOrderNumber',
        'since' => 'setSince',
        'status' => 'setStatus',
        'to' => 'setTo',
        'updated_at' => 'setUpdatedAt'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'in_process_at' => 'getInProcessAt',
        'order_created_at' => 'getOrderCreatedAt',
        'order_id' => 'getOrderId',
        'order_number' => 'getOrderNumber',
        'since' => 'getSince',
        'status' => 'getStatus',
        'to' => 'getTo',
        'updated_at' => 'getUpdatedAt'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['in_process_at'] = isset($data['in_process_at']) ? $data['in_process_at'] : null;
        $this->container['order_created_at'] = isset($data['order_created_at']) ? $data['order_created_at'] : null;
        $this->container['order_id'] = isset($data['order_id']) ? $data['order_id'] : null;
        $this->container['order_number'] = isset($data['order_number']) ? $data['order_number'] : null;
        $this->container['since'] = isset($data['since']) ? $data['since'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['to'] = isset($data['to']) ? $data['to'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets in_process_at
     * @return \Swagger\Client\Model\GetFbsPostingListRequestTimeRange
     */
    public function getInProcessAt()
    {
        return $this->container['in_process_at'];
    }

    /**
     * Sets in_process_at
     * @param \Swagger\Client\Model\GetFbsPostingListRequestTimeRange $in_process_at
     * @return $this
     */
    public function setInProcessAt($in_process_at)
    {
        $this->container['in_process_at'] = $in_process_at;

        return $this;
    }

    /**
     * Gets order_created_at
     * @return \Swagger\Client\Model\GetFbsPostingListRequestTimeRange
     */
    public function getOrderCreatedAt()
    {
        return $this->container['order_created_at'];
    }

    /**
     * Sets order_created_at
     * @param \Swagger\Client\Model\GetFbsPostingListRequestTimeRange $order_created_at
     * @return $this
     */
    public function setOrderCreatedAt($order_created_at)
    {
        $this->container['order_created_at'] = $order_created_at;

        return $this;
    }

    /**
     * Gets order_id
     * @return int
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     * @param int $order_id
     * @return $this
     */
    public function setOrderId($order_id)
    {
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets order_number
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->container['order_number'];
    }

    /**
     * Sets order_number
     * @param string $order_number
     * @return $this
     */
    public function setOrderNumber($order_number)
    {
        $this->container['order_number'] = $order_number;

        return $this;
    }

    /**
     * Gets since
     * @return \DateTime
     */
    public function getSince()
    {
        return $this->container['since'];
    }

    /**
     * Sets since
     * @param \DateTime $since
     * @return $this
     */
    public function setSince($since)
    {
        $this->container['since'] = $since;

        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets to
     * @return \DateTime
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     * @param \DateTime $to
     * @return $this
     */
    public function setTo($to)
    {
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets updated_at
     * @return \Swagger\Client\Model\GetFbsPostingListRequestTimeRange
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     * @param \Swagger\Client\Model\GetFbsPostingListRequestTimeRange $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


