<?php
/**
 * ProductGetProductInfoResponseProduct
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ProductGetProductInfoResponseProduct Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductGetProductInfoResponseProduct implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'productGetProductInfoResponseProduct';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'barcode' => 'string',
        'buybox_price' => 'string',
        'category_id' => 'int',
        'created_at' => '\DateTime',
        'id' => 'int',
        'images' => 'string[]',
        'marketing_price' => 'string',
        'min_ozon_price' => 'string',
        'name' => 'string',
        'offer_id' => 'string',
        'old_price' => 'string',
        'premium_price' => 'string',
        'price' => 'string',
        'recommended_price' => 'string',
        'sku' => 'int',
        'sources' => '\Swagger\Client\Model\GetProductInfoResponseSources[]',
        'state' => 'string',
        'stock' => 'int',
        'stocks' => '\Swagger\Client\Model\ProductGetProductInfoResponseStock',
        'validation_errors' => '\Swagger\Client\Model\GetProductInfoResponseValidationError[]',
        'vat' => 'string',
        'visibility_details' => '\Swagger\Client\Model\GetProductInfoResponseVisibilityDetails',
        'visible' => 'bool'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'barcode' => 'barcode',
        'buybox_price' => 'buybox_price',
        'category_id' => 'category_id',
        'created_at' => 'created_at',
        'id' => 'id',
        'images' => 'images',
        'marketing_price' => 'marketing_price',
        'min_ozon_price' => 'min_ozon_price',
        'name' => 'name',
        'offer_id' => 'offer_id',
        'old_price' => 'old_price',
        'premium_price' => 'premium_price',
        'price' => 'price',
        'recommended_price' => 'recommended_price',
        'sku' => 'sku',
        'sources' => 'sources',
        'state' => 'state',
        'stock' => 'stock',
        'stocks' => 'stocks',
        'validation_errors' => 'validation_errors',
        'vat' => 'vat',
        'visibility_details' => 'visibility_details',
        'visible' => 'visible'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'barcode' => 'setBarcode',
        'buybox_price' => 'setBuyboxPrice',
        'category_id' => 'setCategoryId',
        'created_at' => 'setCreatedAt',
        'id' => 'setId',
        'images' => 'setImages',
        'marketing_price' => 'setMarketingPrice',
        'min_ozon_price' => 'setMinOzonPrice',
        'name' => 'setName',
        'offer_id' => 'setOfferId',
        'old_price' => 'setOldPrice',
        'premium_price' => 'setPremiumPrice',
        'price' => 'setPrice',
        'recommended_price' => 'setRecommendedPrice',
        'sku' => 'setSku',
        'sources' => 'setSources',
        'state' => 'setState',
        'stock' => 'setStock',
        'stocks' => 'setStocks',
        'validation_errors' => 'setValidationErrors',
        'vat' => 'setVat',
        'visibility_details' => 'setVisibilityDetails',
        'visible' => 'setVisible'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'barcode' => 'getBarcode',
        'buybox_price' => 'getBuyboxPrice',
        'category_id' => 'getCategoryId',
        'created_at' => 'getCreatedAt',
        'id' => 'getId',
        'images' => 'getImages',
        'marketing_price' => 'getMarketingPrice',
        'min_ozon_price' => 'getMinOzonPrice',
        'name' => 'getName',
        'offer_id' => 'getOfferId',
        'old_price' => 'getOldPrice',
        'premium_price' => 'getPremiumPrice',
        'price' => 'getPrice',
        'recommended_price' => 'getRecommendedPrice',
        'sku' => 'getSku',
        'sources' => 'getSources',
        'state' => 'getState',
        'stock' => 'getStock',
        'stocks' => 'getStocks',
        'validation_errors' => 'getValidationErrors',
        'vat' => 'getVat',
        'visibility_details' => 'getVisibilityDetails',
        'visible' => 'getVisible'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['barcode'] = isset($data['barcode']) ? $data['barcode'] : null;
        $this->container['buybox_price'] = isset($data['buybox_price']) ? $data['buybox_price'] : null;
        $this->container['category_id'] = isset($data['category_id']) ? $data['category_id'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['images'] = isset($data['images']) ? $data['images'] : null;
        $this->container['marketing_price'] = isset($data['marketing_price']) ? $data['marketing_price'] : null;
        $this->container['min_ozon_price'] = isset($data['min_ozon_price']) ? $data['min_ozon_price'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['offer_id'] = isset($data['offer_id']) ? $data['offer_id'] : null;
        $this->container['old_price'] = isset($data['old_price']) ? $data['old_price'] : null;
        $this->container['premium_price'] = isset($data['premium_price']) ? $data['premium_price'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['recommended_price'] = isset($data['recommended_price']) ? $data['recommended_price'] : null;
        $this->container['sku'] = isset($data['sku']) ? $data['sku'] : null;
        $this->container['sources'] = isset($data['sources']) ? $data['sources'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['stock'] = isset($data['stock']) ? $data['stock'] : null;
        $this->container['stocks'] = isset($data['stocks']) ? $data['stocks'] : null;
        $this->container['validation_errors'] = isset($data['validation_errors']) ? $data['validation_errors'] : null;
        $this->container['vat'] = isset($data['vat']) ? $data['vat'] : null;
        $this->container['visibility_details'] = isset($data['visibility_details']) ? $data['visibility_details'] : null;
        $this->container['visible'] = isset($data['visible']) ? $data['visible'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets barcode
     * @return string
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     * @param string $barcode
     * @return $this
     */
    public function setBarcode($barcode)
    {
        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets buybox_price
     * @return string
     */
    public function getBuyboxPrice()
    {
        return $this->container['buybox_price'];
    }

    /**
     * Sets buybox_price
     * @param string $buybox_price
     * @return $this
     */
    public function setBuyboxPrice($buybox_price)
    {
        $this->container['buybox_price'] = $buybox_price;

        return $this;
    }

    /**
     * Gets category_id
     * @return int
     */
    public function getCategoryId()
    {
        return $this->container['category_id'];
    }

    /**
     * Sets category_id
     * @param int $category_id
     * @return $this
     */
    public function setCategoryId($category_id)
    {
        $this->container['category_id'] = $category_id;

        return $this;
    }

    /**
     * Gets created_at
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param \DateTime $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets images
     * @return string[]
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     * @param string[] $images
     * @return $this
     */
    public function setImages($images)
    {
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets marketing_price
     * @return string
     */
    public function getMarketingPrice()
    {
        return $this->container['marketing_price'];
    }

    /**
     * Sets marketing_price
     * @param string $marketing_price
     * @return $this
     */
    public function setMarketingPrice($marketing_price)
    {
        $this->container['marketing_price'] = $marketing_price;

        return $this;
    }

    /**
     * Gets min_ozon_price
     * @return string
     */
    public function getMinOzonPrice()
    {
        return $this->container['min_ozon_price'];
    }

    /**
     * Sets min_ozon_price
     * @param string $min_ozon_price
     * @return $this
     */
    public function setMinOzonPrice($min_ozon_price)
    {
        $this->container['min_ozon_price'] = $min_ozon_price;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets offer_id
     * @return string
     */
    public function getOfferId()
    {
        return $this->container['offer_id'];
    }

    /**
     * Sets offer_id
     * @param string $offer_id
     * @return $this
     */
    public function setOfferId($offer_id)
    {
        $this->container['offer_id'] = $offer_id;

        return $this;
    }

    /**
     * Gets old_price
     * @return string
     */
    public function getOldPrice()
    {
        return $this->container['old_price'];
    }

    /**
     * Sets old_price
     * @param string $old_price
     * @return $this
     */
    public function setOldPrice($old_price)
    {
        $this->container['old_price'] = $old_price;

        return $this;
    }

    /**
     * Gets premium_price
     * @return string
     */
    public function getPremiumPrice()
    {
        return $this->container['premium_price'];
    }

    /**
     * Sets premium_price
     * @param string $premium_price
     * @return $this
     */
    public function setPremiumPrice($premium_price)
    {
        $this->container['premium_price'] = $premium_price;

        return $this;
    }

    /**
     * Gets price
     * @return string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     * @param string $price
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets recommended_price
     * @return string
     */
    public function getRecommendedPrice()
    {
        return $this->container['recommended_price'];
    }

    /**
     * Sets recommended_price
     * @param string $recommended_price
     * @return $this
     */
    public function setRecommendedPrice($recommended_price)
    {
        $this->container['recommended_price'] = $recommended_price;

        return $this;
    }

    /**
     * Gets sku
     * @return int
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     * @param int $sku
     * @return $this
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets sources
     * @return \Swagger\Client\Model\GetProductInfoResponseSources[]
     */
    public function getSources()
    {
        return $this->container['sources'];
    }

    /**
     * Sets sources
     * @param \Swagger\Client\Model\GetProductInfoResponseSources[] $sources
     * @return $this
     */
    public function setSources($sources)
    {
        $this->container['sources'] = $sources;

        return $this;
    }

    /**
     * Gets state
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     * @param string $state
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets stock
     * @return int
     */
    public function getStock()
    {
        return $this->container['stock'];
    }

    /**
     * Sets stock
     * @param int $stock
     * @return $this
     */
    public function setStock($stock)
    {
        $this->container['stock'] = $stock;

        return $this;
    }

    /**
     * Gets stocks
     * @return \Swagger\Client\Model\ProductGetProductInfoResponseStock
     */
    public function getStocks()
    {
        return $this->container['stocks'];
    }

    /**
     * Sets stocks
     * @param \Swagger\Client\Model\ProductGetProductInfoResponseStock $stocks
     * @return $this
     */
    public function setStocks($stocks)
    {
        $this->container['stocks'] = $stocks;

        return $this;
    }

    /**
     * Gets validation_errors
     * @return \Swagger\Client\Model\GetProductInfoResponseValidationError[]
     */
    public function getValidationErrors()
    {
        return $this->container['validation_errors'];
    }

    /**
     * Sets validation_errors
     * @param \Swagger\Client\Model\GetProductInfoResponseValidationError[] $validation_errors
     * @return $this
     */
    public function setValidationErrors($validation_errors)
    {
        $this->container['validation_errors'] = $validation_errors;

        return $this;
    }

    /**
     * Gets vat
     * @return string
     */
    public function getVat()
    {
        return $this->container['vat'];
    }

    /**
     * Sets vat
     * @param string $vat
     * @return $this
     */
    public function setVat($vat)
    {
        $this->container['vat'] = $vat;

        return $this;
    }

    /**
     * Gets visibility_details
     * @return \Swagger\Client\Model\GetProductInfoResponseVisibilityDetails
     */
    public function getVisibilityDetails()
    {
        return $this->container['visibility_details'];
    }

    /**
     * Sets visibility_details
     * @param \Swagger\Client\Model\GetProductInfoResponseVisibilityDetails $visibility_details
     * @return $this
     */
    public function setVisibilityDetails($visibility_details)
    {
        $this->container['visibility_details'] = $visibility_details;

        return $this;
    }

    /**
     * Gets visible
     * @return bool
     */
    public function getVisible()
    {
        return $this->container['visible'];
    }

    /**
     * Sets visible
     * @param bool $visible
     * @return $this
     */
    public function setVisible($visible)
    {
        $this->container['visible'] = $visible;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


