<?php
/**
 * ReportListRequestReportType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ReportListRequestReportType Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportListRequestReportType {
    const ALL = 'ALL';
    const SELLER_PRODUCTS = 'SELLER_PRODUCTS';
    const SELLER_TRANSACTIONS = 'SELLER_TRANSACTIONS';
    const SELLER_PRODUCT_PRICES = 'SELLER_PRODUCT_PRICES';
    const SELLER_STOCK = 'SELLER_STOCK';
    const SELLER_PRODUCT_MOVEMENT = 'SELLER_PRODUCT_MOVEMENT';
    const SELLER_RETURNS = 'SELLER_RETURNS';
    const SELLER_POSTINGS = 'SELLER_POSTINGS';
    const SELLER_FINANCE = 'SELLER_FINANCE';
    

    
}


