<?php
/**
 * Postingv3FbsPostingDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Postingv3FbsPostingDetailTest Class Doc Comment
 *
 * @category    Class */
// * @description Postingv3FbsPostingDetail
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Postingv3FbsPostingDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Postingv3FbsPostingDetail"
     */
    public function testPostingv3FbsPostingDetail()
    {

    }

    /**
     * Test attribute "additional_data"
     */
    public function testPropertyAdditionalData()
    {

    }

    /**
     * Test attribute "addressee"
     */
    public function testPropertyAddressee()
    {

    }

    /**
     * Test attribute "analytics_data"
     */
    public function testPropertyAnalyticsData()
    {

    }

    /**
     * Test attribute "barcodes"
     */
    public function testPropertyBarcodes()
    {

    }

    /**
     * Test attribute "cancellation"
     */
    public function testPropertyCancellation()
    {

    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {

    }

    /**
     * Test attribute "delivering_date"
     */
    public function testPropertyDeliveringDate()
    {

    }

    /**
     * Test attribute "delivery_method"
     */
    public function testPropertyDeliveryMethod()
    {

    }

    /**
     * Test attribute "delivery_price"
     */
    public function testPropertyDeliveryPrice()
    {

    }

    /**
     * Test attribute "financial_data"
     */
    public function testPropertyFinancialData()
    {

    }

    /**
     * Test attribute "in_process_at"
     */
    public function testPropertyInProcessAt()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {

    }

    /**
     * Test attribute "posting_number"
     */
    public function testPropertyPostingNumber()
    {

    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {

    }

    /**
     * Test attribute "provider_status"
     */
    public function testPropertyProviderStatus()
    {

    }

    /**
     * Test attribute "shipment_date"
     */
    public function testPropertyShipmentDate()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "tpl_integration_type"
     */
    public function testPropertyTplIntegrationType()
    {

    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {

    }

}
