<?php
/**
 * PostingCrossborderPostingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PostingCrossborderPostingTest Class Doc Comment
 *
 * @category    Class */
// * @description PostingCrossborderPosting
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostingCrossborderPostingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PostingCrossborderPosting"
     */
    public function testPostingCrossborderPosting()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "cancel_reason_id"
     */
    public function testPropertyCancelReasonId()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "customer_email"
     */
    public function testPropertyCustomerEmail()
    {

    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {

    }

    /**
     * Test attribute "in_process_at"
     */
    public function testPropertyInProcessAt()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "order_number"
     */
    public function testPropertyOrderNumber()
    {

    }

    /**
     * Test attribute "posting_number"
     */
    public function testPropertyPostingNumber()
    {

    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {

    }

    /**
     * Test attribute "shipment_date"
     */
    public function testPropertyShipmentDate()
    {

    }

    /**
     * Test attribute "shipping_provider_id"
     */
    public function testPropertyShippingProviderId()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "tracking_number"
     */
    public function testPropertyTrackingNumber()
    {

    }

}
