<?php
/**
 * Productv2GetProductInfoResponseResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Productv2GetProductInfoResponseResultTest Class Doc Comment
 *
 * @category    Class */
// * @description Productv2GetProductInfoResponseResult
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Productv2GetProductInfoResponseResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Productv2GetProductInfoResponseResult"
     */
    public function testProductv2GetProductInfoResponseResult()
    {

    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {

    }

    /**
     * Test attribute "buybox_price"
     */
    public function testPropertyBuyboxPrice()
    {

    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {

    }

    /**
     * Test attribute "commissions"
     */
    public function testPropertyCommissions()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {

    }

    /**
     * Test attribute "is_prepayment"
     */
    public function testPropertyIsPrepayment()
    {

    }

    /**
     * Test attribute "is_prepayment_allowed"
     */
    public function testPropertyIsPrepaymentAllowed()
    {

    }

    /**
     * Test attribute "marketing_price"
     */
    public function testPropertyMarketingPrice()
    {

    }

    /**
     * Test attribute "min_ozon_price"
     */
    public function testPropertyMinOzonPrice()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {

    }

    /**
     * Test attribute "old_price"
     */
    public function testPropertyOldPrice()
    {

    }

    /**
     * Test attribute "premium_price"
     */
    public function testPropertyPremiumPrice()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "price_index"
     */
    public function testPropertyPriceIndex()
    {

    }

    /**
     * Test attribute "recommended_price"
     */
    public function testPropertyRecommendedPrice()
    {

    }

    /**
     * Test attribute "sources"
     */
    public function testPropertySources()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "stocks"
     */
    public function testPropertyStocks()
    {

    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {

    }

    /**
     * Test attribute "visibility_details"
     */
    public function testPropertyVisibilityDetails()
    {

    }

    /**
     * Test attribute "visible"
     */
    public function testPropertyVisible()
    {

    }

    /**
     * Test attribute "volume_weight"
     */
    public function testPropertyVolumeWeight()
    {

    }

}
