<?php
/**
 * ResultGetReturnsCompanyFBSItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * apiv1/warehouse.proto
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: release-sapi-516
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResultGetReturnsCompanyFBSItemTest Class Doc Comment
 *
 * @category    Class */
// * @description ResultGetReturnsCompanyFBSItem
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultGetReturnsCompanyFBSItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ResultGetReturnsCompanyFBSItem"
     */
    public function testResultGetReturnsCompanyFBSItem()
    {

    }

    /**
     * Test attribute "accepted_from_customer_moment"
     */
    public function testPropertyAcceptedFromCustomerMoment()
    {

    }

    /**
     * Test attribute "clearing_id"
     */
    public function testPropertyClearingId()
    {

    }

    /**
     * Test attribute "commission"
     */
    public function testPropertyCommission()
    {

    }

    /**
     * Test attribute "commission_percent"
     */
    public function testPropertyCommissionPercent()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "is_moving"
     */
    public function testPropertyIsMoving()
    {

    }

    /**
     * Test attribute "is_opened"
     */
    public function testPropertyIsOpened()
    {

    }

    /**
     * Test attribute "last_free_waiting_day"
     */
    public function testPropertyLastFreeWaitingDay()
    {

    }

    /**
     * Test attribute "moving_to_place_name"
     */
    public function testPropertyMovingToPlaceName()
    {

    }

    /**
     * Test attribute "picking_amount"
     */
    public function testPropertyPickingAmount()
    {

    }

    /**
     * Test attribute "place_id"
     */
    public function testPropertyPlaceId()
    {

    }

    /**
     * Test attribute "posting_number"
     */
    public function testPropertyPostingNumber()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "price_without_commission"
     */
    public function testPropertyPriceWithoutCommission()
    {

    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {

    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "return_date"
     */
    public function testPropertyReturnDate()
    {

    }

    /**
     * Test attribute "return_reason_name"
     */
    public function testPropertyReturnReasonName()
    {

    }

    /**
     * Test attribute "returned_to_seller_date_time"
     */
    public function testPropertyReturnedToSellerDateTime()
    {

    }

    /**
     * Test attribute "returns_keeping_cost"
     */
    public function testPropertyReturnsKeepingCost()
    {

    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "waiting_for_seller_date_time"
     */
    public function testPropertyWaitingForSellerDateTime()
    {

    }

    /**
     * Test attribute "waiting_for_seller_days"
     */
    public function testPropertyWaitingForSellerDays()
    {

    }

}
